---
- hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: copy files
    copy: src=/var/lib/jenkins/workspace/deploy-maven-from-ansible/target/MavenWebApp.war dest=/opt/tomcat/webapps/
